---
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Data From https://www.kaggle.com/niyamatalmass/google-job-skills
*rmd要先處存
```{r}
TestData = read.csv('./DATA/job_skills.csv', quote = "", 
                 row.names = NULL, 
                 stringsAsFactors = FALSE)
str(TestData)

```
#Q:Youtube公司需要什麼人才

```{r, include=FALSE, echo = FALSE}
library(data.table)
library(ggplot2)
library(sqldf)
library(rworldmap)
library(ggmap)
library(mapproj)
library(ggplot2)
library(maptools)
library(maps)
library(wordcloud)
# library(qdap)
library(tm)
library(stringr)
library(SnowballC)   
library(Tmisc)
library(scales)

# =================================================================== #
# Defining all custom functions at the beginning.
# =================================================================== #
# function to aggregate text specific to a single publisher/ media house.
create_text<- function( datadf )
{
    print(nrow(datadf))
    # creating empty array
    textarrdf = c(" ")
    
    for(i in 1:nrow(datadf))
    { 
        temp_arr1 = datadf[i, "Responsibilities"]
        temp_arr2 = datadf[i, "Min_qual"]
        temp_arr3 = datadf[i, "Pref_qual"]
        
        textarrdf = paste(textarrdf, temp_arr1, temp_arr2, temp_arr3, sep = " ")
        
    }
    
    return(textarrdf)
} 

# function to copy to clipboard:
copyfn <- function(z) write.table(z, "clipboard" , sep = "\t", row.names = F)

```

```{r, echo=TRUE, include=FALSE}
# Read input file:
youtube_skills <- data.frame(fread("./DATA/job_skills.csv"))

colnames(youtube_skills) <- c("Company", "Title", "Category", "Location", "Responsibilities", "Min_qual",
                             "Pref_qual")
str(youtube_skills)

```

# 工作類別
```{r, echo = FALSE}
table(youtube_skills$Category)
```
A: 1.Sales & Account Management(168)最多/2.Marketing & Communications (165)次之/3.Finance(115)    

# 學歷
a) 最低學歷要求    
```{r, echo=FALSE, include=TRUE}
youtube_skills$min_degree <- ifelse( grepl("Bachelor", youtube_skills$Min_qual) == TRUE, "Bachelor",
                           ifelse( grepl("BA/BS", youtube_skills$Min_qual)==TRUE, "Bachelor",
                           ifelse( grepl("Master", youtube_skills$Min_qual)==TRUE, "Master",
                           ifelse( grepl("PhD", youtube_skills$Min_qual)== TRUE, "PhD", "other"))))

ggplot(youtube_skills, aes(min_degree)) + 
    geom_bar(aes(y = (..count..)/sum(..count..)), fill = "lightblue") + 
    scale_y_continuous(labels=scales::percent) +
    ylab("relative frequencies")
```
A:Bachelor(學士)    
  
b) youtube公司喜歡錄用什麼學歷    
```{r, echo=FALSE, include=TRUE}
youtube_skills$pref_degree <- ifelse( grepl("PhD", youtube_skills$Pref_qual) == TRUE, "PhD",
                          ifelse( grepl("Master", youtube_skills$Pref_qual)==TRUE, "Master",
                          ifelse( grepl("MBA", youtube_skills$Pref_qual)==TRUE, "Master",
                          ifelse( grepl("MS", youtube_skills$Pref_qual)== TRUE, "Master", "Bachelor"))))

ggplot(youtube_skills, aes(pref_degree)) + 
    geom_bar(aes(y = (..count..)/sum(..count..)), fill = "lightblue") + 
    scale_y_continuous(labels=scales::percent) +
    ylab("relative frequencies")
```
A:Bachelor(學士)    

#對於Youtube公司來說什麼最重要

```{r, echo=FALSE, include=FALSE}


text_dict_source <- subset(youtube_skills)

row.names(text_dict_source) <- NULL


text_sourcedf <- create_text( text_dict_source)

text_sourcedf2 <- iconv(text_sourcedf, "latin1", "ASCII", sub="")

text_sourcedf2 = tolower(text_sourcedf2)



wordCorpus <- Corpus(VectorSource(text_sourcedf2))
summary(wordCorpus)


wordCorpus <- tm_map(wordCorpus, removePunctuation)
wordCorpus <- tm_map(wordCorpus, removeNumbers)
wordCorpus <- tm_map(wordCorpus, content_transformer(tolower))
wordCorpus <- tm_map(wordCorpus, removeWords, stopwords("english"))
wordCorpus <- tm_map(wordCorpus, stripWhitespace)
wordCorpus <- tm_map(wordCorpus, stemDocument) 




wordCorpus1 <- tm_map(wordCorpus, stemDocument)

```

```{r, echo=FALSE, include=TRUE}
wordcloud(wordCorpus1, scale=c(5,0.5), max.words=100, random.order=FALSE, 
          rot.per=0.35, use.r.layout=FALSE, colors = brewer.pal(8, "Dark2"))
```    
    
A:最看重經驗，管理能力次之，最後是工作與個人能力    


